name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - test_fix_commit_history_status_list
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"
      - "templates/**"
      - "utils/**"

jobs:
  run_push_ci:
    name: Run Push CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout transformers
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Checkout to branch push-ci
        # A more strict way to make sure`push-ci` is exactly the same as `main` at the push event commit.
        run: |
          sleep 5m 30s
          git checkout -b push-ci
          git push -u origin push-ci --force
